### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by harikt** [harikt/web.expressive#8]
Laravel have something like `redirect()->back()->withInput()->withErrors()` . Need to bring the errors / input back after redirect.

**Comment by IHackPy** [comment]
I would like to work on this Issue

**Comment by harikt** [comment]
Hi @HimanshuAwasthi95 , 

Thank you for your interest working on this.

You may want to look into how the laravel function `redirect` is making use of `with` , `withErrors`, `withInput` etc. This is what I think, we may need to save these in a Aura.Session flash, and then get this on the next request. The result we obtained need to be converted to `Illuminate\Support\MessageBag` which is actually used inside blade.

Let me know if you need anything else. I do understand this probably is not an easy task, but can understand / follow the internals even if you cannot make this happen.

Thank you for your time.

**Comment by harikt** [comment]
This is partially done via https://github.com/harikt/web.expressive/pull/34 and looks like a good start.

**Comment by harikt** [comment]
Closing this now.  This will be fixed via issues #47 and #48 .
